config/routes.rb
Rails.application.routes.draw do
  resources :pizza_carts
  resources :carts
  resources :pizza_in_orders
  resources :delivery_infos
  resources :orders
  devise_for :customers, :controllers => { registrations: 'registrations' }
  resources :pizzas
  resources :ingredient_recipes
  resources :recipes
  resources :crusts
  resources :ingredients
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  root to: 'application#index'
  get 'my_cart', to: 'carts#show'
  post 'add_to_cart', to: 'pizzas#create', as: 'add_to_cart'
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/cart.rb
class Cart < ApplicationRecord
  belongs_to :customer
  has_many :pizza_carts
  has_many :pizzas, through: :pizza_carts
end

app/models/crust.rb
class Crust < ApplicationRecord
  validates :price, presence: true, numericality: { only_integer: true }
end

app/models/customer.rb
class Customer < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
  has_many :orders
  has_one :cart
  validates :name, presence: true
end

app/models/delivery_info.rb
class DeliveryInfo < ApplicationRecord
  belongs_to :customer
  validates :address1, presence: true
  validates :phone, numericality: true, presence: true
end

app/models/ingredient.rb
class Ingredient < ApplicationRecord
  validates :name, presence: true, uniqueness: true
end

app/models/ingredient_recipe.rb
class IngredientRecipe < ApplicationRecord
  belongs_to :recipe
  belongs_to :ingredient
  validates :recipe_id, presence: true
  validates :ingredient_id, presence: true
end

app/models/order.rb
class Order < ApplicationRecord
  belongs_to :customer
  has_one :delivery_info
  has_many :pizzas
  validates :payment, presence: true
  validates :pizzas, length: { minimum: 1 }
end

app/models/pizza.rb
class Pizza < ApplicationRecord
  belongs_to :crust
  belongs_to :recipe
  has_one :order
  has_many :ingredients, through: :recipe
end

app/models/pizza_cart.rb
class PizzaCart < ApplicationRecord
  belongs_to :pizza
  belongs_to :cart
end

app/models/pizza_in_order.rb
class PizzaInOrder < ApplicationRecord
  belongs_to :order
  belongs_to :pizza
end

app/models/recipe.rb
class Recipe < ApplicationRecord
  has_many :ingredient_recipes
  has_many :ingredients, through: :ingredient_recipes
  validates :price, presence: true, numericality: { only_integer: true }
  validates :name, presence: true
end

app/controllers/carts_controller.rb
class CartsController < ApplicationController
  before_action :set_cart, only: [:edit, :update, :destroy]

  # GET /carts
  # GET /carts.json
  def index
    @carts = Cart.all
  end

  # GET /carts/1
  # GET /carts/1.json
  def show
    @cart = Cart.find_by_customer_id(current_customer.id)
    if @cart.nil?
      @cart = Cart.new
      @cart.customer = current_customer
      @cart.save
    end
    @delivery_info = DeliveryInfo.new
  end

  # GET /carts/new
  def new
    @cart = Cart.new
  end

  # GET /carts/1/edit
  def edit
  end

  # POST /carts
  # POST /carts.json
  def create
    @cart = Cart.new(cart_params)

    respond_to do |format|
      if @cart.save
        format.html { redirect_to @cart, notice: 'Cart was successfully created.' }
        format.json { render :show, status: :created, location: @cart }
      else
        format.html { render :new }
        format.json { render json: @cart.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /carts/1
  # PATCH/PUT /carts/1.json
  def update
    respond_to do |format|
      if @cart.update(cart_params)
        format.html { redirect_to @cart, notice: 'Cart was successfully updated.' }
        format.json { render :show, status: :ok, location: @cart }
      else
        format.html { render :edit }
        format.json { render json: @cart.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /carts/1
  # DELETE /carts/1.json
  def destroy
    @cart.destroy
    respond_to do |format|
      format.html { redirect_to carts_url, notice: 'Cart was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_cart
      @cart = Cart.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def cart_params
      params.require(:cart).permit(:customer_id)
    end
end

app/controllers/crusts_controller.rb
class CrustsController < ApplicationController
  before_action :set_crust, only: [:show, :edit, :update, :destroy]

  # GET /crusts
  # GET /crusts.json
  def index
    @crusts = Crust.all
  end

  # GET /crusts/1
  # GET /crusts/1.json
  def show
  end

  # GET /crusts/new
  def new
    @crust = Crust.new
  end

  # GET /crusts/1/edit
  def edit
  end

  # POST /crusts
  # POST /crusts.json
  def create
    @crust = Crust.new(crust_params)

    respond_to do |format|
      if @crust.save
        format.html { redirect_to @crust, notice: 'Crust was successfully created.' }
        format.json { render :show, status: :created, location: @crust }
      else
        format.html { render :new }
        format.json { render json: @crust.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /crusts/1
  # PATCH/PUT /crusts/1.json
  def update
    respond_to do |format|
      if @crust.update(crust_params)
        format.html { redirect_to @crust, notice: 'Crust was successfully updated.' }
        format.json { render :show, status: :ok, location: @crust }
      else
        format.html { render :edit }
        format.json { render json: @crust.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /crusts/1
  # DELETE /crusts/1.json
  def destroy
    @crust.destroy
    respond_to do |format|
      format.html { redirect_to crusts_url, notice: 'Crust was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_crust
      @crust = Crust.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def crust_params
      params.require(:crust).permit(:thin, :price)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/carts_helper.rb
module CartsHelper
end

app/helpers/crusts_helper.rb
module CrustsHelper
end

app/helpers/ingredients_helper.rb
module IngredientsHelper
end

app/helpers/orders_helper.rb
module OrdersHelper
end

app/helpers/pizza_carts_helper.rb
module PizzaCartsHelper
end

app/helpers/pizzas_helper.rb
module PizzasHelper
end

app/helpers/recipes_helper.rb
module RecipesHelper
end

app/helpers/registrations_helper.rb
module RegistrationsHelper
end

app/views/carts/_form.html.erb
<%= form_with(model: cart, local: true) do |form| %>
  <% if cart.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(cart.errors.count, "error") %> prohibited this cart from being saved:</h2>

      <ul>
      <% cart.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :customer_id %>
    <%= form.text_field :customer_id %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/carts/edit.html.erb
<h1>Editing Cart</h1>

<%= render 'form', cart: @cart %>

<%= link_to 'Show', @cart %> |
<%= link_to 'Back', carts_path %>

app/views/carts/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Carts</h1>

<table>
  <thead>
    <tr>
      <th>Customer</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @carts.each do |cart| %>
      <tr>
        <td><%= cart.customer %></td>
        <td><%= link_to 'Show', cart %></td>
        <td><%= link_to 'Edit', edit_cart_path(cart) %></td>
        <td><%= link_to 'Destroy', cart, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Cart', new_cart_path %>

app/views/carts/new.html.erb
<h1>New Cart</h1>

<%= render 'form', cart: @cart %>

<%= link_to 'Back', carts_path %>

app/views/carts/show.html.erb
<h1><%= @cart.customer.name %>'s card</h1>

<table class="table">
  <thead>
  <tr>
    <th>Pizza</th>
    <th>Thin crust?</th>
    <th>Price + crust</th>
  </tr>
  </thead>

  <tbody>
  <% total = 0 %>
  <% @cart.pizzas.each do |pizza| %>
    <tr>
      <td><%= pizza.recipe.name %></td>
      <% if pizza.crust.thin %>
        <td>Yes</td>
      <% else %>
        <td>No</td>
      <% end %>
      <td>$ <%= pizza.crust.price + pizza.recipe.price %></td>
      <% total += pizza.crust.price + pizza.recipe.price %>
    </tr>
  <% end %>
  </tbody>
  <tr>
    <td>Total:</td>
    <td></td>
    <td>$ <%= total %></td>
  </tr>
</table>

<h2>Payment and Delivery</h2>
<%= form_for @delivery_info do |form| %>
  <div class="field">
    <%= form.label :customer_id %>
    <%= form.text_field :customer_id %>
  </div>

  <div class="field">
    <%= form.label :address1 %>
    <%= form.text_field :address1 %>
  </div>

  <div class="field">
    <%= form.label :address2 %>
    <%= form.text_field :address2 %>
  </div>

  <div class="field">
    <%= form.label :phone %>
    <%= form.number_field :phone %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/crusts/_form.html.erb
<%= form_with(model: crust, local: true) do |form| %>
  <% if crust.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(crust.errors.count, "error") %> prohibited this crust from being saved:</h2>

      <ul>
      <% crust.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :thin %>
    <%= form.check_box :thin %>
  </div>

  <div class="field">
    <%= form.label :price %>
    <%= form.number_field :price %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/crusts/edit.html.erb
<h1>Editing Crust</h1>

<%= render 'form', crust: @crust %>

<%= link_to 'Show', @crust %> |
<%= link_to 'Back', crusts_path %>

app/views/crusts/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Crusts</h1>

<table>
  <thead>
    <tr>
      <th>Thin</th>
      <th>Price</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @crusts.each do |crust| %>
      <tr>
        <td><%= crust.thin %></td>
        <td><%= crust.price %></td>
        <td><%= link_to 'Show', crust %></td>
        <td><%= link_to 'Edit', edit_crust_path(crust) %></td>
        <td><%= link_to 'Destroy', crust, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Crust', new_crust_path %>

app/views/crusts/new.html.erb
<h1>New Crust</h1>

<%= render 'form', crust: @crust %>

<%= link_to 'Back', crusts_path %>

app/views/crusts/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Thin:</strong>
  <%= @crust.thin %>
</p>

<p>
  <strong>Price:</strong>
  <%= @crust.price %>
</p>

<%= link_to 'Edit', edit_crust_path(@crust) %> |
<%= link_to 'Back', crusts_path %>