config/routes.rb
Rails.application.routes.draw do
  resources :pizza_carts
  resources :carts
  resources :pizza_in_orders
  resources :delivery_infos
  resources :orders
  devise_for :customers, :controllers => { registrations: 'registrations' }
  resources :pizzas
  resources :ingredient_recipes
  resources :recipes
  resources :crusts
  resources :ingredients
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  root to: 'application#index'
  get 'my_cart', to: 'carts#show'
  post 'add_to_cart', to: 'pizzas#create', as: 'add_to_cart'
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/cart.rb
class Cart < ApplicationRecord
  belongs_to :customer
  has_many :pizza_carts
  has_many :pizzas, through: :pizza_carts
end

app/models/crust.rb
class Crust < ApplicationRecord
  validates :price, presence: true, numericality: { only_integer: true }
end

app/models/customer.rb
class Customer < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
  has_many :orders
  has_one :cart
  validates :name, presence: true
end

app/models/delivery_info.rb
class DeliveryInfo < ApplicationRecord
  belongs_to :customer
  validates :address1, presence: true
  validates :phone, numericality: true, presence: true
end

app/models/ingredient.rb
class Ingredient < ApplicationRecord
  validates :name, presence: true, uniqueness: true
end

app/models/ingredient_recipe.rb
class IngredientRecipe < ApplicationRecord
  belongs_to :recipe
  belongs_to :ingredient
  validates :recipe_id, presence: true
  validates :ingredient_id, presence: true
end

app/models/order.rb
class Order < ApplicationRecord
  belongs_to :customer
  has_one :delivery_info
  has_many :pizzas
  validates :payment, presence: true
  validates :pizzas, length: { minimum: 1 }
end

app/models/pizza.rb
class Pizza < ApplicationRecord
  belongs_to :crust
  belongs_to :recipe
  has_one :order
  has_many :ingredients, through: :recipe
end

app/models/pizza_cart.rb
class PizzaCart < ApplicationRecord
  belongs_to :pizza
  belongs_to :cart
end

app/models/pizza_in_order.rb
class PizzaInOrder < ApplicationRecord
  belongs_to :order
  belongs_to :pizza
end

app/models/recipe.rb
class Recipe < ApplicationRecord
  has_many :ingredient_recipes
  has_many :ingredients, through: :ingredient_recipes
  validates :price, presence: true, numericality: { only_integer: true }
  validates :name, presence: true
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/carts_helper.rb
module CartsHelper
end

app/helpers/crusts_helper.rb
module CrustsHelper
end

app/helpers/ingredients_helper.rb
module IngredientsHelper
end

app/helpers/orders_helper.rb
module OrdersHelper
end

app/helpers/pizza_carts_helper.rb
module PizzaCartsHelper
end

app/helpers/pizzas_helper.rb
module PizzasHelper
end

app/helpers/recipes_helper.rb
module RecipesHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Examen AZ</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
    <link rel="stylesheet" href="https://use.fontawesome.com/releases/v5.0.13/css/all.css" integrity="sha384-DNOHZ68U8hZfKXOrtjWvjxusGo9WQnrNx2sqG0tfsghAvtVlRW3tvkXWZh58N9jp" crossorigin="anonymous">
    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <nav class="navbar navbar-expand-sm bg-dark navbar-dark">
      <div class="container">
        <ul class="navbar-nav">
          <%= link_to 'Home', root_path, class: 'navbar-brand' %>
          <li class="nav-item active">
            <a class="nav-link" href="#">Active</a>
          </li>
          <li class="nav-item">
            <a class="nav-link" href="#">Link</a>
          </li>
          <li class="nav-item">
            <a class="nav-link" href="#">Link</a>
          </li>
          <li class="nav-item">
            <a class="nav-link disabled" href="#">Disabled</a>
          </li>
        </ul>
        <ul class="nav navbar-nav navbar-right">
          <% if customer_signed_in? %>
            <li class="nav-item">
              <%= link_to '<i class="fas fa-shopping-cart"></i>'.html_safe, my_cart_path, class: 'nav-link' %>
            </li>
            <li class="nav-item">
              <%= link_to('Logout', destroy_customer_session_path, method: :delete, class: 'nav-link') %>
            </li>
          <% else %>
            <li class="nav-item">
              <%= link_to('Login', new_customer_session_path, class: 'nav-link') %>
            </li>
          <% end %>
        </ul>
      </div>
    </nav>
    <div class="container">
      <p class="notice"><%= notice %></p>
      <p class="alert"><%= alert %></p>
      <%= yield %>
    </div>
  </body>
</html>